name: Dependabot Security Alerts

on:
  workflow_dispatch:

jobs:
  dependabot-security-alerts:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Dependabot Security Alerts
      uses: dependabot/dependabot-core@0.167.x
      with:
        args: "security --format=json"
      id: dependabot-security-alerts
    - name: Print Security Alerts
      run: |
        echo "${{ steps.dependabot-security-alerts.outputs.result }}" | jq '.[].title'
