name: Process Dependabot Pull Requests
on:
  workflow_dispatch:
jobs:
  process-dependabot-pulls:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Process Pull Requests
        run: |
          curl -H "Authorization: Bearer ${{ secrets.DEPENDABOT_PR }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/pulls?state=open | \
          jq '[.[] | select(.user.login == "dependabot[bot]") | {created_at, severity: .labels[] | select(.name | startswith("dependabot/")) | .name}] | group_by(.severity) | map({severity: .[0].severity, count: length, months: [.[] | {month: .created_at | strptime("%Y-%m-%dT%H:%M:%SZ") | todate | strftime("%Y-%m"), count: 1}] | group_by(.month)}) | map({severity: .severity, count: .count, months: [.[] | {month: .[0].month, count: . | length}]})' \
          > dependabot_pulls.json
        env:
          GITHUB_TOKEN: ${{ secrets.DEPENDABOT_PR }}
      - name: Upload Results
        uses: actions/upload-artifact@v2
        with:
          name: Dependabot Pulls
          path: dependabot_pulls.json
