name: Dependabot Issues

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  dependabot-issues:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Dependabot Issues
      uses: dependabot/dependabot-core@0.167.x
      with:
        args: "metadata --format=json"
      id: dependabot-issues
    - name: Print Issues
      run: |
        echo "${{ steps.dependabot-issues.outputs.result }}" | jq '.[].title'
