name: Dependabot Issues

on:
  workflow_dispatch:

jobs:
  dependabot-issues:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Get Dependabot Issues
      run: |
        dependabot issues list --format=json > issues.json
    - name: Print Dependabot Issues
      run: |
        cat issues.json
