name: Dependabot Security Alerts

on:
  workflow_dispatch:

jobs:
  list-security-alerts:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: List Security Alerts
      run: |
        curl -s -H "Authorization: Bearer ${{ secrets.DEPENDABOT_PR }}" \
        "https://api.github.com/repos/${{ github.repository }}/security/alerts" \
        | jq -r '.[] | [.affected_package_name, .affected_range, .severity] | @csv'
