name: Process Dependabot Pull Requests
on:
  workflow_dispatch:
jobs:
  process-dependabot-pulls:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Process Pull Requests
        run: |
          curl -H "Authorization: Bearer ${{ secrets.DEPENDABOT_PR }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/pulls?state=open | \
          jq '[.[] | select(.user.login == "dependabot[bot]") | {number, created_at, severity: .labels[] | select(.name | startswith("dependabot/")) | .name}] | group_by(.severity) | map({severity: .[0].severity, pulls: [.[] | {number, month: .created_at | strptime("%Y-%m-%dT%H:%M:%SZ") | todate | strftime("%Y-%m"), changes: []}] | group_by(.month)}) | .[] | .pulls[] | select(length > 0) | .changes |= (reduce .[] as $item ([]; . + [$item.number])) | {severity: .severity, month: .month, changes: .changes}' \
          > dependabot_pulls.json
        env:
          GITHUB_TOKEN: ${{ secrets.DEPENDABOT_PR }}
      - name: Create Pull Requests
        run: |
          cat dependabot_pulls.json | jq -c '. | {title: "Dependabot Updates for \(.month) (\(.severity))", body: "This PR contains updates from Dependabot for \(.month) with severity \(.severity).", head: "dependabot_updates/\(.month)_\(.severity)", base: "master"}' | \
          while read -r pr_data; do \
            curl -H "Authorization: Bearer ${{ secrets.DEPENDABOT_PR }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d "$pr_data" \
            https://api.github.com/repos/${{ github.repository }}/pulls ; \
          done
        env:
          GITHUB_TOKEN: ${{ secrets.DEPENDABOT_PR }}
